source:      .

permalink:	/:title

exclude: [Gruntfile.js, package.json, node_modules, assets/less]

title:		Strip
tagline: 'Site tagline'
description:	'Site description'
tags: 'tags'
url:		http://internets.com

project:
  name: project
  url: http://grginc.github.io/ios-bootstrap
  github: https://github.com/grginc/ios-bootstrap
  download: http://codeload.github.com/grginc/ios-bootstrap/zip/master